services:
  openvpn:
    container_name: openvpn
    restart: unless-stopped
    image: dperson/openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./volumes/openvpn/vpn:/vpn:ro
    ports:
      - 8081:8080
    networks:
      default:
        ipv4_address: 10.1.5.2
  tor:
    container_name: tor
    restart: unless-stopped
    image: osminogin/tor-simple
    depends_on:
      - openvpn
    ports:
      - 9050:9050
    networks:
      default:
        ipv4_address: 10.1.5.3
  forward-proxy:
    container_name: nginx
    image: dominikbechstein/nginx-forward-proxy
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
    network_mode: service:openvpn

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.1.5.0/24
          gateway: 10.1.5.1
